import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { ConvexClientProvider } from "@/components/convexClientProvider";
import { ClerkProvider } from '@clerk/nextjs';

const inter = Inter({subsets:["latin"],});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}`}
      >
      <ClerkProvider>
        <ConvexClientProvider>
        <Header/>
        <main>{children}</main>
        </ConvexClientProvider>
      </ClerkProvider>
      </body>
    </html>
  );
}
